### PR TITLE
feat: added reaction-analytics button

### PR DESCRIPTION
**Pull request by pranavmene2000**
reaction![Capture]

In case of multiple users:
(https://github.com/user-attachments/assets/7c4c0d6b-af89-4ac8-bad2-e67f0c7b7f3a)

### CODE REVIEW

**Comment by janhvipatil** [comment]
@pranavmene2000 The count over here should be 5 right?
(https://github.com/user-attachments/assets/7c4c0d6b-af89-4ac8-bad2-e67f0c7b7f3a)

Also, rather than having count as a separate column, can we combine the emoji and count in one column like so -
Screenshot 2024-08-12 at 8 51 37 PM

**Comment by pranavmene2000** [comment]
Yes. This is just an example. I edited dom to add users, so that I can take screenshot.
But anyway, it will give the correct count once as per the number of users.

**Comment by janhvipatil** [comment]
Oh okay, also do we have a scroll inside if the users are over 1000?

**Comment by pranavmene2000** [comment]
> Oh okay, also do we have a scroll inside if the users are over 1000?

Inner Scroller:
reaction-scroller

**Pull request closed without merging**
