### PR TITLE
build: use workspaces

### PR DESCRIPTION
**Pull request by blaggacao**
Like other Frappe apps.

This, at the very least, avoids build issues (to be documented below): 

This blocks: https://github.com/blaggacao/frappix/pull/10

### CODE REVIEW

**Comment by nikkothari22** [comment]
@blaggacao The base branch is "develop". Not main. We'll merge develop into main when we make a new release (which should be today)

**Comment by nikkothari22** [comment]
Ah it looks like you created the branch from main.

**Comment by blaggacao** [comment]
Nice! Thanks a lot, your reaction time is refreshing and much appreciated. Thank you! :handshake:

**Comment by nikkothari22** [comment]
Looks like builds are failing on Frappe Cloud :(

image


Might be related to this?

**Comment by nikkothari22** [comment]
Fixed the build issue via: https://github.com/The-Commit-Company/Raven/commit/25a1b8cb060708bd580e2a84f3e448fdcc4f215d . Missed the extra workspace here.

**Comment by blaggacao** [comment]
Ah! I'm sorry for the oversight. It had a `package.json`, so I heuristically added it.

**Pull request merged**
