### PR TITLE
feat: show system messages when channel members are changed

### PR DESCRIPTION
**Pull request by nikkothari22**
CleanShot 2024-10-11 at 19 43 26@2x

### CODE REVIEW

**Comment by zaheer-srushty** [comment]
I just wanted to understand the workflow for this use case

Say, an employee A creates a Private Raven channel and adds employee B & C to the channel. Now, when the employee A leaves the organization, we mark the employee as Left in the HRMS & the user_id is disabled. In this case, the Raven Channel Member doctype for that user is still active and hence the switchover of Admin role to employee B never happens.

Can you explain how is this envisioned in Raven for switchover to occur automatically?

**Comment by nikkothari22** [comment]
@zaheer-srushty Maybe we need to trigger the admin change if a user is disabled (there's a disabled flag in Raven User doctype). Currently, we don't do that, but it makes sense. Will create an issue for this. Should the disabled member be removed from all channels?

**Comment by zaheer-srushty** [comment]
Yes. The disabled member should be removed from all channels & threads... Also, I noticed that we are still able to send messages to a disabled user in a DM...I think the DM channel input should also be disabled...

**Comment by zaheer-srushty** [comment]
@nikkothari22 I think the system messages should be centered similar to the Date separator rather than having it aligned with the channel messages.

**Comment by nikkothari22** [comment]
That was the initial thought. We tried that, it didn't look good, especially when you have a lot of them.

**Pull request merged**
